# -*- coding: utf-8 -*-
"""
/***************************************************************************
                                 A QGIS plugin
 Generated by Plugin Builder: https://github.com/wamartinez
                             -------------------
        begin                : 2021-06-04
        git sha              : $Format:%H$
        copyright            : (C) 2021
        email                : willimarti@gmail.com
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QWidget, QDockWidget, QGridLayout, QPushButton, QLineEdit, QToolButton, QLabel
from qgis.PyQt.QtGui import QIcon, QPixmap


class CoordinateCaptureDockWidget(QDockWidget):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(CoordinateCaptureDockWidget, self).__init__(parent)

        self.setWindowTitle(self.tr("Coordinate of the position"))
        self.setGeometry(0, 0, 300, 228)
        self.dockWidgetContents = QWidget(self)
        self.setWidget(self.dockWidgetContents)
        self.gridLayout = QGridLayout()
        self.dockWidgetContents.setLayout(self.gridLayout)

        self.dockWidgetContents.layout().setColumnMinimumWidth(0, 36)

        self.userCrsEdit = QLineEdit(self.dockWidgetContents)
        self.userCrsEdit.setReadOnly(True)
        self.userCrsEdit.setToolTip(self.tr("Coordinate in your selected CRS (lat,lon)"))
        self.copyUserCrsCoordinatesAction = self.userCrsEdit.addAction(QIcon(":/plugins/GEETrajectories/mActionEditCopy.svg"),
                                                                       QLineEdit.TrailingPosition)
        self.copyUserCrsCoordinatesAction.triggered.connect(self.copyUserCrsCoordinates)

        # Create the action for tool
        self.captureButton = QPushButton(self.dockWidgetContents)
        self.captureButton.setText(self.tr("Start Capture of position"))
        self.captureButton.setToolTip(self.tr("Click to enable coordinate capture"))
        self.captureButton.setIcon(QIcon(":/plugins/GEETrajectories/icon_cursor.jpg"))
        self.captureButton.setWhatsThis(self.tr("Click on the map to view coordinates and capture to clipboard."))

        self.dockWidgetContents.layout().addWidget(self.userCrsEdit, 0, 1)
        self.dockWidgetContents.layout().addWidget(self.captureButton, 2, 1)

    def copyUserCrsCoordinates(self):
        self.userCrsEdit.selectAll()
        self.userCrsEdit.copy()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
